services:
  - type: web
    name: pingme-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    healthCheckPath: /
    rootDir: ./Server
  
  - type: web
    name: pingme-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    rootDir: ./Client
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
